//----------------------- MyTestCase.java ------------------------
package test;

import module.NewUIModule;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.telluriumsource.test.java.TelluriumJUnitTestCase;
import org.telluriumsource.test.java.TelluriumJavaTestCase;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * Created by IntelliJ IDEA.
 * User: ikeda_yusuke
 * Date: 11/12/27
 * Time: 18:37
 * To change this template use File | Settings | File Templates.
 */
/**
 *	This test file (MyTestCase.java) is automatically generated by TrUMP 0.8.0.
 *
 */

public class NewTestCase extends TelluriumJavaTestCase {

    private static NewUIModule num;

    @BeforeClass
    public static void initUi() {
        num = new NewUIModule();
        num.defineUi();
        connectSeleniumServer();
        useTelluriumEngine(true);
        useTrace(true);
    }

    @Before
    public void setUpForTest() {
        connectUrl("http://code.google.com/p/aost/downloads/list");
    }

    //Add your test cases here
    @Test
    public void testTelluriumProjectPage(){
        String[] allTypes = num.getAllDownloadTypes();
        assertNotNull(allTypes);
        assertTrue(allTypes[1].contains("All downloads"));
        num.selectDownloadType(allTypes[1]);
        num.searchDownload("TrUMP");
    }

    @AfterClass
    public static void tearDown(){
        showTrace();
    }
}
