package module

import org.telluriumsource.dsl.DslContext

/**
 *	This UI module file (MyUiModule.groovy) is automatically generated by TrUMP 0.8.0.
 *	For any problems, please report to Tellurium User Group at: 
 *		http://groups.google.com/group/tellurium-users
 *
 *	Example: Google Search Module
 *
 *		ui.Container(uid: "Google", clocator: [tag: "td"]){
 *			InputBox(uid: "Input", clocator: [title: "Google Search"]
 *			SubmitButton(uid: "Search", clocator: [name: "btnG", value: "Google Search"]
 *			SubmitButton(uid: "ImFeelingLucky", clocator: [value: "I'm Feeling Lucky"]
 *		}
 *
 *		public void doGoogleSearch(String input) {
 *			keyType "Google.Input", input
 *			click "Google.Search"
 *			waitForPageToLoad 30000
 *		}
 *
 */

class NewUIModule extends DslContext {

    public void defineUi() {
        ui.Form(uid: "TelluriumDownload", clocator: [tag: "form", method: "GET", action: "list"], group: "true"){
            Selector(uid: "DownloadType", clocator: [tag: "select", direct: "true", name: "can", id: "can"])
            InputBox(uid: "input", clocator: [tag: "input", type: "text", name: "q", id: "searchq"])
            SubmitButton(uid: "Search", clocator: [tag: "input", direct: "true", type: "submit", value: "Search"])
        }
    }

    //Add your methods here
    public void searchDownload(String keyword) {
        keyType "TelluriumDownload.input", keyword
        click "TelluriumDownload.Search"
        waitForPageToLoad 30000
    }

    public String[] getAllDownloadTypes() {
        return getSelectOptions("TelluriumDownload.DownloadType")
    }

    public void selectDownloadType(String type) {
        selectByLabel "TelluriumDownload.DownloadType", type
    }
}